# -*- coding: utf-8 -*-
import json, random, sys, os
sys.stdout.reconfigure(encoding='utf-8')
random.seed(2437)

BASE = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(BASE, 'canals_data.json'), encoding='utf-8') as f:
    canals = json.load(f)

zones = [
    (42.90, 71.37, 'Тараз'),
    (43.05, 72.80, 'Шу'),
    (42.70, 70.50, 'Жуалы'),
    (43.30, 73.50, 'Мойынкум'),
    (42.50, 71.80, 'Байзак'),
    (43.60, 70.80, 'Мерки'),
    (42.80, 72.20, 'Кордай'),
    (43.10, 71.00, 'Жамбыл'),
]

# Real river polylines + oblast boundary (from geoBoundaries + OpenStreetMap).
# Generated by process_rivers.py — single source of truth shared with app.js.
with open(os.path.join(BASE, 'rivers_data.json'), encoding='utf-8') as f:
    _geo = json.load(f)
RIVER_LINES = _geo['rivers']          # name -> [[lat,lon], ...]  (real coordinates)
BOUNDARY = _geo['boundary']           # [[lat,lon], ...]          (real oblast outline)

def in_boundary(lat, lon):
    inside = False
    n = len(BOUNDARY); j = n - 1
    for i in range(n):
        yi, xi = BOUNDARY[i]; yj, xj = BOUNDARY[j]
        if ((xi > lon) != (xj > lon)) and \
           (lat < (yj - yi) * (lon - xi) / ((xj - xi) or 1e-12) + yi):
            inside = not inside
        j = i
    return inside

def point_along_source(src, t):
    """Point at fraction t along the real river line, nudged slightly off the
    centerline but always kept INSIDE the oblast boundary (no desert points)."""
    line = RIVER_LINES.get(src)
    if not line or len(line) < 2:
        return None
    seg = t * (len(line) - 1)
    i = min(int(seg), len(line) - 2)
    f = seg - i
    (la1, lo1), (la2, lo2) = line[i], line[i + 1]
    la = la1 + (la2 - la1) * f
    lo = lo1 + (lo2 - lo1) * f
    dla, dlo = la2 - la1, lo2 - lo1
    length = (dla * dla + dlo * dlo) ** 0.5 or 1
    pla, plo = -dlo / length, dla / length
    # try a few small offsets, accept the first that stays inside the boundary
    for off_scale in (0.012, 0.006, 0.0):
        off = (random.random() - 0.5) * off_scale
        nla = la + pla * off
        nlo = lo + plo * off
        if in_boundary(nla, nlo):
            return round(nla, 5), round(nlo, 5)
    return round(la, 5), round(lo, 5)

# Source assignment cycle (name, t_lo, t_hi) — spreads objects ALONG each real
# river over the given fraction range so every watercourse gets filled.
# The Chu is capped at 0.85 to avoid its deep NW desert tail.
SOURCE_CYCLE = [
    ('р. Шу (Чу)', 0.0, 0.85), ('р. Талас', 0.0, 1.0), ('р. Аса', 0.0, 1.0),
    ('р. Аспара', 0.0, 1.0), ('р. Боралдай', 0.0, 1.0),
    ('р. Шу (Чу)', 0.0, 0.85), ('р. Талас', 0.0, 1.0), ('р. Аса', 0.0, 1.0),
    ('р. Аспара', 0.0, 1.0), ('Тасоткельское вдхр.', 0.0, 1.0),
    ('Терс-Ащибулакское вдхр.', 0.0, 1.0),
]

# District centroids (inside the real boundary) — object district is the
# geographically nearest one, so the label always matches the location.
DISTRICT_CENTROIDS = {
    'Тараз':    (42.90, 71.39), 'Байзак': (43.05, 71.18), 'Жамбыл': (43.18, 70.90),
    'Жуалы':    (42.95, 70.50), 'Таласский': (42.55, 71.95), 'Мерки': (42.86, 73.18),
    'Кордай':   (43.10, 74.40), 'Шу': (43.62, 73.75), 'Мойынкум': (44.30, 72.60),
}

def nearest_district(lat, lon):
    best, bd = 'Тараз', 1e9
    for name, (la, lo) in DISTRICT_CENTROIDS.items():
        d = (la - lat) ** 2 + (lo - lon) ** 2
        if d < bd:
            bd, best = d, name
    return best

DEFECT_CATALOG = {
    'critical': [
        {'code':'D01','name':'Суффозия и трубчатая фильтрация','desc':'Вынос грунта через тело сооружения (piping). Признаки: мутные выходы воды у подошвы, воронки на гребне.','remedy':'Немедленная цементная инъекция тела сооружения, устройство противофильтрационной диафрагмы.','urgency':'немедленно'},
        {'code':'D02','name':'Нарушение устойчивости откоса','desc':'Оползневые деформации верхового или низового откоса дамбы. Трещины под углом 30-45° к оси.','remedy':'Разгрузка откоса, устройство контрбанкета из гравия, бурение дренажных скважин.','urgency':'немедленно'},
        {'code':'D03','name':'Критическая сверхнормативная фильтрация','desc':'Потери воды >40% от подачи. Прорывная фильтрация в основании канала.','remedy':'Срочная противофильтрационная завеса, укладка геомембраны ПВД по всему ложу.','urgency':'немедленно'},
        {'code':'D04','name':'Полное разрушение облицовки','desc':'Разрушение бетонной облицовки на >60% площади. Размыв откосов.','remedy':'Капитальный ремонт: укладка бетонной облицовки М200 толщ. 10 см на геотекстиль.','urgency':'1-3 дня'},
        {'code':'D05','name':'Отказ водовыпускного затвора','desc':'Затвор не открывается/закрывается из-за коррозии или деформации рамы. Угроза неуправляемого сброса.','remedy':'Замена привода затвора, ревизия направляющих и уплотнений, смазка шпинделя.','urgency':'1-3 дня'},
    ],
    'warning': [
        {'code':'D06','name':'Трещины в теле канала','desc':'Продольные трещины шириной 3-8 мм по гребню сооружения. Возможен прорыв при паводке.','remedy':'Расшивка трещин, заполнение цементным молоком, установка маяков-щелемеров.','urgency':'1 месяц'},
        {'code':'D07','name':'Повышенная фильтрация (КПД ниже нормы)','desc':'Фактическое КПД ниже проектного на >20%. Потери воды 15-40%.','remedy':'Установка пьезометров вдоль канала, картирование фильтрационных потерь, инъекционное укрепление.','urgency':'2 недели'},
        {'code':'D08','name':'Эрозия откосов волнением','desc':'Поверхностная эрозия от волнового воздействия. Промоины глубиной 5-15 см, обнажение грунтовой подготовки.','remedy':'Ремонт крепления откоса: гравийный рипрап или монолитные железобетонные плиты.','urgency':'1 месяц'},
        {'code':'D09','name':'Кольматация дренажной системы','desc':'Снижение дренажного расхода >30%. Повышение уровня грунтовых вод у подошвы.','remedy':'Промывка дренажных трубофильтров под давлением 0.3 МПа, замена засорённых участков.','urgency':'2 недели'},
        {'code':'D10','name':'Неравномерная осадка гребня','desc':'Дифференциальная осадка 5-12 см по длине сооружения. Деформация опалубки.','remedy':'Геодезическое нивелирование марок, анализ грунтов основания, при необходимости усиление.','urgency':'1 месяц'},
    ],
    'ok': [
        {'code':'D11','name':'Плановый осмотр','desc':'Сооружение в нормативном состоянии. Плановая инспекция согласно регламенту РГП «Казводхоз».','remedy':'Выполнить визуальный осмотр, замер фильтрационных расходов, нивелирование репперов.','urgency':'по графику'},
        {'code':'D12','name':'Биологическое зарастание откосов','desc':'Частичное зарастание берегов водной растительностью (камыш, рогоз). Снижение расхода на 5%.','remedy':'Механическая очистка русла от водной растительности, скашивание 1 раз в сезон.','urgency':'3 месяца'},
        {'code':'D13','name':'Износ уплотнений затвора','desc':'Незначительная протечка через уплотнения затвора (<0.5 л/с). Ресурс уплотнений исчерпан.','remedy':'Плановая замена резиновых уплотнений при ежегодном техническом обслуживании.','urgency':'6 месяцев'},
    ]
}

SENSOR_FAULTS = [
    {'code':'SF01','component':'Датчик расхода (ультразвуковой)','fault':'Засорение пьезопреобразователей осадком','detail':'Сигнал нестабилен ±0.3 м/с. Осадок и биоплёнка на ультразвуковых излучателях блокируют акустический луч, снижая точность измерения скорости течения.','fix':'Механическая очистка преобразователей ёршиком + промывка 5% лимонной кислотой. Проверка калибровки по эталонному расходу.','priority':'средний'},
    {'code':'SF02','component':'Датчик уровня воды (радарный)','fault':'Смещение нулевой отметки после ледохода','detail':'Показания завышены на 0.15-0.25 м. Нарушена привязка к репперу после механического воздействия льдин при ледоходе.','fix':'Повторная калибровка по установочной рейке, проверка и затяжка крепёжного кронштейна.','priority':'средний'},
    {'code':'SF03','component':'Датчик температуры (Pt100)','fault':'Электрохимическая коррозия зонда','detail':'Зонд даёт завышенные показания (+2-4°C). Окисление контактов корпуса в минерализованной воде (проводимость >700 мкС/см).','fix':'Замена зонда Pt100 из нержавеющей стали AISI-316, обработка корпуса антикоррозийным покрытием.','priority':'низкий'},
    {'code':'SF04','component':'Датчик мутности (турбидиметр)','fault':'Биообрастание оптической линзы','detail':'Показания мутности завышены в 2-3 раза. Водоросли и биоплёнка на оптической линзе вызывают ложное рассеяние светового пучка.','fix':'Установка автоматического скребкового очистителя (wiper) + обработка 0.5 мг/л сульфата меди.','priority':'средний'},
    {'code':'SF05','component':'pH-электрод','fault':'Засорение диафрагмы электрода','detail':'Дрейф показаний pH ±0.4 ед. Засорение пористой диафрагмы кальциевыми отложениями (жёсткость воды до 8 мг-экв/л).','fix':'Замена электрода, промывка 0.1М соляной кислотой, установка защитного сетчатого колпачка.','priority':'низкий'},
    {'code':'SF06','component':'Кабельная линия связи (RS-485)','fault':'Обрыв кабеля из-за ледовой нагрузки','detail':'Датчик полностью офлайн. Механический обрыв подводного кабеля в прибрежной зоне при ледоходе.','fix':'Прокладка резервного кабеля в защитном кожухе ПНД Ø50 мм на глубину 0.5 м от дна канала.','priority':'высокий'},
    {'code':'SF07','component':'Аккумулятор датчика (AGM 12В)','fault':'Деградация АКБ при температурных перепадах','detail':'Заряд <20%, автономность снижена с 72 до 8 часов. Диапазон температур -35..+45°C разрушает пластины АКБ за 2-3 сезона.','fix':'Замена AGM-аккумулятора 12В/26Ач, установка термоизолирующего бокса из пенополиуретана 50 мм.','priority':'высокий'},
    {'code':'SF08','component':'Электрод проводимости','fault':'Карбонатные отложения на электродах','detail':'Показания занижены на 15-20%. Карбонатная накипь CaCO3 на платиновых электродах при высокой минерализации воды >800 мг/л.','fix':'Очистка электродов 5% уксусной кислотой, повторная калибровка по стандарт-раствору KCl.','priority':'низкий'},
    {'code':'SF09','component':'Поплавок уровнемера','fault':'Намотка растительности на трос','detail':'Показания уровня не изменяются (застревание поплавка). Водная растительность и ветки намотались на трос при паводке.','fix':'Очистка троса и направляющих, установка защитного цилиндра из нержавеющей сетки Ø200 мм.','priority':'средний'},
]

for i, c in enumerate(canals):
    c['id'] = i + 1                       # guarantee unique ids (source had dupes)
    # Assign source from the weighted cycle so all rivers get filled evenly
    src, t_lo, t_hi = SOURCE_CYCLE[i % len(SOURCE_CYCLE)]
    c['source'] = src
    # Place the object ALONG its real water source (spread over the t-range)
    t = t_lo + random.random() * (t_hi - t_lo)
    pt = point_along_source(src, t)
    c['lat'], c['lon'] = pt
    # District = geographically nearest centroid, so the label matches location
    c['zone'] = nearest_district(pt[0], pt[1])

    age = 2026 - c['year'] if c['year'] else 50
    kpd_loss = max(0, c['kpd_proj'] - c['kpd_fact']) / max(c['kpd_proj'], 0.01)
    risk = min(100, int(age*0.3 + c['wear']*30 + kpd_loss*40 + (20 if c['condition']=='не удов.' else 0)))
    c['risk_score'] = risk
    c['status'] = 'critical' if risk>=70 or c['condition']=='не удов.' else 'warning' if risk>=40 else 'ok'
    c['status_label'] = {'critical':'Требует ремонта','warning':'Требует осмотра','ok':'Норма'}[c['status']]
    c['inspection_months'] = 3 if c['status']=='critical' else 6 if c['status']=='warning' else 12

    defect_pool = DEFECT_CATALOG[c['status']]
    c['defect'] = defect_pool[i % len(defect_pool)]

    has_fault = random.random() < 0.32
    sensor_fault = random.choice(SENSOR_FAULTS) if has_fault else None

    base_flow = max(0.05, c['capacity'] * c['kpd_fact'] * random.uniform(0.6,0.95)) if c['capacity'] else random.uniform(0.1,1.2)
    base_temp = random.uniform(10.0, 24.0)
    history = [{'h':h,'f':round(max(0,base_flow+(random.random()-0.5)*0.15),3),'t':round(base_temp+(random.random()-0.5)*1.5,1)} for h in range(12)]

    flow = round(max(0, base_flow + random.uniform(-0.1,0.1)), 3)
    temp = round(base_temp + random.uniform(-0.5,0.5), 1)
    level = round(random.uniform(0.5,1.9), 2)
    turb = round(random.uniform(3,40), 1)
    ph = round(random.uniform(6.8,8.2), 1)
    cond = int(random.uniform(200,900))
    online = not (sensor_fault and sensor_fault['code']=='SF06')

    alerts = []
    if level > 1.7: alerts.append({'type':'critical','msg':'Критический уровень воды'})
    if turb > 30: alerts.append({'type':'warning','msg':'Высокая мутность'})
    if temp > 22: alerts.append({'type':'info','msg':'Повышенная температура воды'})
    if not online: alerts.append({'type':'critical','msg':'Датчик не в сети'})
    if sensor_fault:
        prio = sensor_fault['priority']
        t = 'critical' if prio=='высокий' else 'warning'
        alerts.append({'type':t,'msg':f"Неисправность: {sensor_fault['fault']}"})

    c['sensors'] = {
        'flow_speed': flow, 'temperature': temp, 'water_level': level,
        'turbidity': turb, 'ph': ph, 'conductivity': cond,
        'online': online, 'battery': random.randint(15,100),
        'last_update': f'2026-06-25 {random.randint(8,23):02d}:{random.randint(0,59):02d}',
        'history': history, 'alerts': alerts, 'fault': sensor_fault
    }

RESERVOIRS = [
    {'id':'r1','name':'Тасоткельское водохранилище','river':'р. Шу','type':'reservoir',
     'capacity_mln':1120,'year':1968,'lat':43.12,'lon':72.57,'status':'ok','zone':'Шу',
     'desc':'Многолетнее регулирование стока р. Шу. Площадь зеркала 620 км², объём 1120 млн м³. Орошение 130 000 га Шуского района.',
     'defect':{'code':'D11','name':'Плановый осмотр','desc':'Сооружение в рабочем состоянии. Требуется плановое обследование плотины и водосброса.','remedy':'Визуальный осмотр тела плотины, замер фильтрации, нивелирование гребня.','urgency':'6 месяцев'}},
    {'id':'r2','name':'Кировское водохранилище','river':'р. Талас','type':'reservoir',
     'capacity_mln':580,'year':1965,'lat':42.80,'lon':71.52,'status':'warning','zone':'Тараз',
     'desc':'Водоснабжение Тараза и орошение 75 000 га. Объём 580 млн м³. Земляная плотина высотой 68 м.',
     'defect':{'code':'D07','name':'Повышенная фильтрация через тело плотины','desc':'Потери воды через тело плотины превышают норму на 18%. Фиксируется пьезометрами П-12, П-17.','remedy':'Установка дополнительных пьезометров, анализ фильтрационного потока. При подтверждении — цементная завеса.','urgency':'2 недели'}},
    {'id':'r3','name':'Терс-Ащибулакское вдхр.','river':'р. Терс','type':'reservoir',
     'capacity_mln':310,'year':1972,'lat':43.08,'lon':70.55,'status':'ok','zone':'Жамбыл',
     'desc':'Комплексное водохранилище на р. Терс. Ирригация Жамбылского района, объём 310 млн м³.',
     'defect':{'code':'D12','name':'Биологическое зарастание чаши','desc':'Зарастание мелководий водной растительностью. Снижение полезного объёма на 3-5%.','remedy':'Механическая очистка зоны мелководий 1 раз в 2 года. Контроль батиметрии.','urgency':'3 месяца'}},
    {'id':'r4','name':'Байдибекское водохранилище','river':'р. Байдибек','type':'reservoir',
     'capacity_mln':85,'year':1981,'lat':42.76,'lon':70.32,'status':'critical','zone':'Жуалы',
     'desc':'Малое вдхр. для орошения. Объём 85 млн м³. Требует капитального ремонта плотины.',
     'defect':{'code':'D02','name':'Нарушение устойчивости низового откоса','desc':'Оползневые деформации на низовом откосе плотины. Трещина длиной 47 м на отм. 842 м. Критическое состояние.','remedy':'Разгрузка откоса, устройство контрбанкета из гравия, бурение дренажных скважин. СРОЧНО.','urgency':'немедленно'}},
    {'id':'r5','name':'Аспаринское водохранилище','river':'р. Аспара','type':'reservoir',
     'capacity_mln':42,'year':1977,'lat':42.70,'lon':73.46,'status':'ok','zone':'Кордай',
     'desc':'Сезонное регулирование стока для орошения Кордайского района. Объём 42 млн м³.',
     'defect':{'code':'D13','name':'Износ уплотнений водосбросного затвора','desc':'Незначительная протечка через уплотнения донного водосброса. Расход утечки ~0.3 л/с.','remedy':'Плановая замена резиновых уплотнений при следующем техническом обслуживании.','urgency':'6 месяцев'}},
    {'id':'r6','name':'Шаульдерское водохранилище','river':'р. Шу','type':'reservoir',
     'capacity_mln':95,'year':1984,'lat':43.95,'lon':70.80,'status':'warning','zone':'Мерки',
     'desc':'Регулирование паводков р. Шу в нижнем течении. Объём 95 млн м³.',
     'defect':{'code':'D10','name':'Неравномерная осадка гребня плотины','desc':'Дифференциальная осадка гребня 8 см за последние 3 года. Превышает нормативные показатели.','remedy':'Нивелирование реперных марок (12 шт.), анализ грунтов основания. При подтверждении — усиление.','urgency':'1 месяц'}},
]

out = os.path.join(BASE, 'data.js')
with open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write('const CANALS_DATA=')
    f.write(json.dumps(canals, ensure_ascii=True, separators=(',',':')))
    f.write(';\nconst RESERVOIRS=')
    f.write(json.dumps(RESERVOIRS, ensure_ascii=True, separators=(',',':')))
    f.write(';\n')

sz = os.path.getsize(out)
print(f'OK: data.js {sz/1024:.0f} KB | {len(canals)} каналов | {len(RESERVOIRS)} вдхр.')
